name: Build APK
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build APK with Official Kivy Buildozer Action
      uses: kivy/buildozer-action@v1
      with:
        COMMAND: buildozer -v android debug
